/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CertificateVerifierInterface extends Interface {
  getFunction(
    nameOrSignature: "certificateIssuer" | "registerHash" | "verifyHash"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CertificateRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "certificateIssuer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHash",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "certificateIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
}

export namespace CertificateRegisteredEvent {
  export type InputTuple = [
    hash: BytesLike,
    registrant: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    hash: string,
    registrant: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    hash: string;
    registrant: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertificateVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): CertificateVerifier;
  waitForDeployment(): Promise<this>;

  interface: CertificateVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certificateIssuer: TypedContractMethod<[], [string], "view">;

  registerHash: TypedContractMethod<
    [_certificateHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyHash: TypedContractMethod<
    [_certificateHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certificateIssuer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerHash"
  ): TypedContractMethod<[_certificateHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<[_certificateHash: BytesLike], [boolean], "view">;

  getEvent(
    key: "CertificateRegistered"
  ): TypedContractEvent<
    CertificateRegisteredEvent.InputTuple,
    CertificateRegisteredEvent.OutputTuple,
    CertificateRegisteredEvent.OutputObject
  >;

  filters: {
    "CertificateRegistered(bytes32,address,uint256)": TypedContractEvent<
      CertificateRegisteredEvent.InputTuple,
      CertificateRegisteredEvent.OutputTuple,
      CertificateRegisteredEvent.OutputObject
    >;
    CertificateRegistered: TypedContractEvent<
      CertificateRegisteredEvent.InputTuple,
      CertificateRegisteredEvent.OutputTuple,
      CertificateRegisteredEvent.OutputObject
    >;
  };
}
